select * from information_schema.tables

select * from information_schema.columns


select * from information_schema.columns
where table_name='dim_customer'

--explore all countries our customers come from

select distinct country from gold.dim_customers

--explore all categories the major divisions
select distinct category from gold.dim_products

select distinct category, subcategory from gold.dim_products

select distinct category, subcategory, product_name from gold.dim_products
order by 1,2,3


--find the date of the first and last order
select 

	min(order_date) as first_order_date,
	max(order_date) as last_order_date,
	datediff(month,min(order_date),max(order_date)) as order_range_years_months

from gold.fact_sales

-- find the youngest and oldest customer
select
	min(birthdate) as oldest_birthdate,
	max(birthdate) as youngest_birthdate,

	datediff(year,min(birthdate),getdate()) as oldest_age,
	datediff(year,max(birthdate),getdate()) as youngest_age
from gold.dim_customers

--Measure exploration

-- find the total sales
select sum(sales_amount) as total_sales from gold.fact_sales

-- find how many items are sold
select sum(quantity) as total_quantity from gold.fact_sales
--find the average selling price
select avg(price) as avg_price from gold.fact_sales
--find the total number of orders
select count(order_number) as total_orders from gold.fact_sales
select count(distinct order_number) as total_orders from gold.fact_sales
--find the total number of products
select count(distinct product_key) as total_products from gold.dim_products
--find the total number of customers
select count(customer_key) as total_customers from gold.dim_customers
--find the total number of customers that has placed an order
select count(distinct customer_key) as total_customers from gold.dim_customers

--generate report that shows all key metrics of the business
select 'total_sales' as measure_name, sum(sales_amount) as measure_value from gold.fact_sales
union all

select 'total_quantity', sum(quantity) as measure_value from gold.fact_sales
union all
select 'average_price',avg(price) from gold.fact_sales
union all
select 'total_orders',count(distinct order_number) from gold.fact_sales
union all
select 'total_products',count(product_name) from gold.dim_products
union all
select 'total_customers',count(customer_key) from gold.dim_customers

-- find total customers by countries
select
country,count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc

--find total customers by gender

select
gender,count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc

--find total products by category
select category,
count(product_key) as total_products
from gold.dim_products
group by category
order by total_products desc

--what is the average costs in each category

select category,
avg(cost) as avg_costs
from gold.dim_products
group by category
order by avg_costs desc

--what is the total revenue is generated for each category
select p.category,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key=f.product_key
group by p.category
order by total_revenue desc

--find total revenue is generated by each customer
select
	c.customer_key,
	c.first_name,
	c.last_name,
	sum(f.sales_amount) as total_revenue
	from gold.fact_sales f
	left join gold.dim_customers c
	on c.customer_key=f.customer_key
	group by c.customer_key,
	c.first_name,
	c.last_name
order by total_revenue desc

--what is the distribution of sold items across countries

select
	c.country,
	sum(f.quantity) as total_sold_items
	from gold.fact_sales f
	left join gold.dim_customers c
	on c.customer_key=f.customer_key
	group by c.country
	
order by total_sold_items desc


--ranking analysis
-- which 5 products generate the highest revenue
select top 5
p.product_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key=f.product_key
group by p.product_name
order by total_revenue desc


select *
from( select
p.product_name,
sum(f.sales_amount) as total_revenue,
row_number() over(order by sum(f.sales_amount) desc) as rank_products
from gold.fact_sales f
left join gold.dim_products p
on p.product_key=f.product_key
group by p.product_name)t
where rank_products <=5


--what are the 5 worst performing products in terms of sales
select top 5
p.product_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key=f.product_key
group by p.product_name
order by total_revenue 

/* find the top 10 customers who have generated the highest revenue
and 3 customers with the fewest orders placed */

select top 10
	c.customer_key,
	c.first_name,
	c.last_name,
	sum(f.sales_amount) as total_revenue
	from gold.fact_sales f
	left join gold.dim_customers c
	on c.customer_key=f.customer_key
	group by c.customer_key,
	c.first_name,
	c.last_name
order by total_revenue desc


select top 3
	c.customer_key,
	c.first_name,
	c.last_name,
	count(distinct order_number) as total_orders
	from gold.fact_sales f
	left join gold.dim_customers c
	on c.customer_key=f.customer_key
	group by 
	c.customer_key,
	c.first_name,
	c.last_name
order by total_orders 